export enum QueryKeyEnum {
  GAS_PRICES = 'GAS_PRICES',
  FAVORITE_LIST = 'FAVORITE_LIST',

  ROUTE_PARAMS = 'ROUTE_PARAMS',

  LAST_SYNCED_HEIGHT = 'LAST_SYNCED_HEIGHT',
  USER_BALANCE_ADDRESS = 'USER_BALANCE_ADDRESS',
  TX_INFO = 'TX_INFO',

  // Trade
  BUY_MAX_FROM = 'BUY_MAX_FROM',

  // CW20
  TOKEN_INFO = 'TOKEN_INFO',
  WHITELIST_CW20_BALANCE = 'WHITELIST_CW20_BALANCE',
  LPOFLPLIST_CW20_BALANCE = 'LPOFLPLIST_CW20_BALANCE',
  CW20_BALANCE = 'CW20_BALANCE',
  CW20USTLP_BALANCE = 'CW20USTLP_BALANCE',
  POOL = 'POOL',
  POOL_LIST = 'POOL_LIST',
  POOL_INFO = 'POOL_INFO',
  SIMULATE = 'SIMULATE',
  TX_HISTORY = 'TX_HISTORY',

  // Limit order
  LIMIT_ORDER_ORDER = 'LIMIT_ORDER_ORDER',
  LIMIT_ORDER_ORDERS = 'LIMIT_ORDER_ORDERS',
  LIMIT_ORDER_CONFIG = 'LIMIT_ORDER_CONFIG',

  // MIAW
  ADDRESS_NAME = 'ADDRESS_NAME',
  BURN_HISTORY = 'BURN_HISTORY',
  BURN_LEADERBOARD = 'BURN_LEADERBOARD',

  // terra swap api
  HISTORICAL_DATA = 'HISTORICAL_DATA',

  // LP Staking
  LPSTAKING_CONFIG = 'LPSTAKING_CONFIG',
  LPSTAKING_STATE = 'LPSTAKING_STATE',
  LPSTAKING_INFO = 'LPSTAKING_INFO',
}
